name: Publish to Arch User Repository (AUR)

on:
  release:
    types: [ published ]

jobs:
  publish_aur_package:
    name: 'Publish to AUR'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download archive
        run: wget https://github.com/sidusio/boogrocha/archive/${GITHUB_REF##*/}.tar.gz

      - name: Update PKGBUILD
        run: |
          tag=${GITHUB_REF##*/}
          hash=$(sha256sum $tag.tar.gz | awk '{print $1;}')
          sed -i "s/tag=/tag=$tag/g" build/PKGBUILD
          sed -i "s/sha256sums=/sha256sums=('$hash')/g" build/PKGBUILD

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.0
        with:
          pkgname: boogrocha
          pkgbuild: build/PKGBUILD
          commit_username: githubaction
          commit_email: boogrocha@sidus.io
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          force_push: true # optional, default is false
